### ISSUE TITLE
Show CMC USD+BTC price

### ISSUE THREAD

**Issue by leto** [matthewjamesr/hush-ng#43]
https://api.coinmarketcap.com/v1/ticker/hush/

**Comment by OleksandrBlack** [comment]
@leto Not sure, or it will help you. https://github.com/MyHush/hush-ng/pull/44

```
function priceHUSH() {
	jQuery.getJSON('https://api.coinmarketcap.com/v1/ticker/hush/?convert=EUR')
		.done(function(data){
			$('.hush_usd').text(data[0]['price_usd']);
			$('.hush_eur').text(data[0]['price_eur']);
			$('.hush_btc').text(data[0]['price_btc']);
	    });
}
priceHUSH();
setInterval(priceHUSH, 20000);
```

```
USD: <span class="hush_usd"></span>
EUR: <span class="hush_eur"></span>
BTC: <span class="hush_btc"></span>
```

**Comment by leto** [comment]
Working on it in `dev_fee` branch

**Comment by leto** [comment]
![hush-cmc-prices](https://user-images.githubusercontent.com/30298/38812993-9c43db18-4142-11e8-8ec4-44050848d35b.png)
was my first hack at it and now it looks like:
![hush-cmc-prices2](https://user-images.githubusercontent.com/30298/38813032-b71390b4-4142-11e8-9211-f450cde23ead.png)

@OleksandrBlack thanks for your help, we are using the same API 😄 

Also planning on adding the daily/weekly/monthly percent changes, that takes some more work.

**Comment by OleksandrBlack** [comment]
@leto 
take a look at my pr https://github.com/MyHush/hush-ng/pull/44

`https://api.coinmarketcap.com/v1/ticker/hush/?convert=EUR`
**?convert=EUR** - Provides an opportunity to withdraw information in Euro
